-- ============================================================
-- DEPRECATED — use the main script instead:
--
--   docker exec -e PGPASSWORD=postgres -i supabase_db_pickd psql -U supabase_admin -d postgres < supabase/create_users.sql
--
-- Or run the full sync which includes user creation:
--
--   bash scripts/sync-local-db.sh
-- ============================================================
