-- Hardening: register_new_sku must NOT create a duplicate when a canonical
-- SKU (same normalized form) already exists in sku_metadata.
--
-- Background — bug 2026-05-01:
--   `sku_metadata` accumulated 19 dup pairs like (`03-4664BR`, `034664BR`),
--   (`010400`, '01-0400'), etc. Generated by callers (CorrectionMode "Create
--   New SKU", FedEx Returns intake) passing dash-stripped SKUs from PDFs to
--   register_new_sku, which previously did `INSERT ... ON CONFLICT DO NOTHING`
--   on the EXACT SKU. The exact-match conflict didn't fire because the
--   stripped form is a different string from the canonical, so a new row
--   was inserted side-by-side. Watchdog's fuzzy lookup later races between
--   them (dict-comprehension last-write-wins) and sometimes resolves PDFs
--   to the bogus row, leaving the order with sku_not_found / no inventory.
--
-- Fix:
--   Before INSERT, call lookup_canonical_sku(p_sku). If a canonical exists,
--   reuse it and DO NOT create the duplicate. Return the canonical SKU
--   (and a `created_canonical_redirect` flag) so callers know the resolved
--   SKU may differ from the requested one.
--
-- Affected callers (all already read result.sku from the RPC return —
-- naturally adapt without code changes):
--   - src/features/labels/components/InlineSkuCreate.tsx
--   - src/features/fedex-returns/components/ReturnToStockSheet.tsx
--   - src/features/fedex-returns/hooks/useFedExReturns.ts (intake placeholder)

CREATE OR REPLACE FUNCTION public.register_new_sku(
  p_sku text,
  p_item_name text,
  p_warehouse text DEFAULT 'LUDLOW',
  p_location text DEFAULT 'INCOMING'
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_location_id uuid;
  v_sku text := upper(trim(p_sku));
  v_name text := trim(p_item_name);
  v_location text := upper(trim(p_location));
  v_canonical_count int;
  v_canonical_sku text;
  v_redirected boolean := false;
BEGIN
  -- Validate inputs
  IF v_sku = '' OR v_sku IS NULL THEN
    RAISE EXCEPTION 'SKU cannot be empty' USING ERRCODE = '22023';
  END IF;
  IF v_name = '' OR v_name IS NULL THEN
    RAISE EXCEPTION 'Item name cannot be empty' USING ERRCODE = '22023';
  END IF;
  IF v_location = '' OR v_location IS NULL THEN
    v_location := 'INCOMING';
  END IF;

  -- Canonical-form check: if a sku_metadata row exists whose normalized
  -- form matches and is NOT the exact same string we're inserting, redirect
  -- to that canonical instead of creating a duplicate.
  -- (lookup_canonical_sku already excludes the exact match.)
  SELECT COUNT(*), MIN(sku) INTO v_canonical_count, v_canonical_sku
  FROM public.lookup_canonical_sku(v_sku);

  -- Only redirect when there's a single unambiguous canonical. >1 means
  -- two existing rows already share a normalized form (a dup we haven't
  -- cleaned up yet) — don't pick one arbitrarily, fall through to the
  -- normal flow with the input SKU.
  IF v_canonical_count = 1 THEN
    v_sku := v_canonical_sku;
    v_redirected := true;
  END IF;

  -- Create sku_metadata if not exists (dimensions/weight filled later).
  INSERT INTO sku_metadata (sku)
  VALUES (v_sku)
  ON CONFLICT (sku) DO NOTHING;

  -- Resolve location (auto-creates in locations table if needed)
  v_location_id := resolve_location(p_warehouse, v_location, 'admin');

  -- Create inventory row with qty=0 (bike hasn't arrived yet)
  INSERT INTO inventory (sku, warehouse, location, location_id, quantity, is_active, item_name)
  VALUES (v_sku, p_warehouse, v_location, v_location_id, 0, true, v_name)
  ON CONFLICT DO NOTHING;

  RETURN jsonb_build_object(
    'sku', v_sku,
    'item_name', v_name,
    'location', v_location,
    'location_id', v_location_id,
    'canonical_redirect', v_redirected
  );
END;
$$;
